config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Scales routes
resources :scales, only: [:index, :new, :create, :update, :destroy]
get '/scales/most_popular', to: 'scales#most_popular', as: 'most_popular_scale'
get '/scales/:scale_slug', to: 'scales#show'
get '/scales/:scale_slug/edit', to: 'scales#edit', as: 'edit_scale'
post '/scales/:scale_slug/change_root', to: 'scales#change_root'
get '/scales/:scale_slug/:root_note', to: 'scales#show', as: 'show_scale'



resources :practises, only: [:create]

# Sessions routes
get '/login', to: 'sessions#new', as: 'login'
get '/auth/:provider/callback', to: 'sessions#create' # OAuth callback route
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'

# Users (musicians) routes
resources :musicians, only: [:new, :create]
get '/musicians/rankings/:by', to: 'musicians#rankings', as: 'musician_rankings'
get '/:musician_slug', to: 'musicians#show', as: 'practice_room'

root 'welcome#welcome'


end

app/models/scale.rb
class Scale < ApplicationRecord
  validates :pattern, presence: {:message => "needs at least two notes!"}
  validates :pattern, uniqueness: {:message => "already belongs to another scale!"}
  validates :name, presence: true
  validates_format_of :name, :with => /\A([\w\ |(|)|-|\d|\#])*\z/m, :message => "can only contain alphanumeric characters, spaces and the # sign!"
  validates :name, uniqueness: {:case_sensitive => false, :message => "is already is use for another scale!"}
  validates :scale_type, presence: true
  validates_format_of :scale_type, :with => /\A([\w\ |-|(|)\d|\#])*\z/, :message => "can only contain alphanumeric characters, spaces and the # sign!"

  has_many :practises
  has_many :musicians, through: :practises


  # Class methods
  def self.types #returns all the unique scale types
    all.map{|s|s.scale_type}.uniq
  end

  def self.find_by_slug(slug) #eg. find "Jazz minor" from 'jazz-minor'
    find{|s| s.slugify == slug}
  end

  def self.standard_index
    Scale.all.select{|s| s.private == false}.sort_by{|s| s.name}
  end

  def self.custom_index(user)  #returns a list of scales visible to the user (based on permissions and private/public scale status)
    Scale.all.select{|s| s.private == false || s.created_by == user.id}.sort_by{|s| s.name}
  end

  def self.create_custom(user, params) #create a new scale
    new_scale = Scale.new(name: params[:name], scale_type: params[:scale_type], origin: params[:origin], melody_rules: params[:melody_rules])
    new_scale.pattern = Scale.custom_pattern(params[:pattern])
    new_scale.private = false if params[:private] == "0"
    new_scale.created_by = user.id
    new_scale
  end

  def self.custom_pattern(midi_array) #converts the form data into a numerical code that represents the scale
    pattern = []
    midi_array.shift if midi_array[0] == ""
    midi_array.each_with_index do |note, i|
      (pattern << (midi_array[i+1].to_i - midi_array[i].to_i)) unless i == midi_array.size - 1
    end
    pattern.join
  end

  # Instance methods
  def custom_update(scale, params) #update a scale
    scale.update(params)
    scale.pattern = Scale.custom_pattern(params[:pattern])
    if params[:private] == "1"
      scale.private = true
    elsif params[:private] == "0"
      scale.private = false
    end
  end

  def slugify #eg. make 'f-sharp' from 'f#'
    name.gsub(" ", "-").gsub("#","sharp")
  end

end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController

  def index
    @scales = Scale.custom_index(current_user)
    @types = Scale.types
  end

  def show
    root_note = Note.get_root(params)
    @scale = Scale.find_by_slug(params[:scale_slug])
    if valid_scale?(@scale)
      @midi_notes = @scale.midi_generator(root_note, 1)
      @current_root = params[:root_note]
      @roots = Note.references
      @practise = Practise.new(scale: @scale)
      @owner = Musician.find(@scale.created_by)
      @your_practise = current_user.find_scale(@scale)
    end
  end

  def change_root
    scale = Scale.find_by_slug(params[:scale_slug])
    go_to(scale, params[:root])
  end

  def new
    @scale = Scale.new
    @note_selection = Note.references
    @pattern = []
  end

  def create
    @scale = Scale.create_custom(current_user, scale_params)
    if @scale.save
      go_to(@scale)
    else
      @note_selection = Note.references
      @pattern = @scale.midi_generator(60, 1)
      render :new
    end
  end

  def edit
    @scale = Scale.find_by_slug(params[:scale_slug])
    if editable_scale?(@scale)
      @note_selection = Note.references
      @pattern = @scale.midi_generator(60, 1)
    end
  end

  def update
    @scale = Scale.find(params[:id])
    editable_scale?(@scale)
    @scale.custom_update(@scale, scale_params)
    if @scale.save
      go_to(@scale)
    else
      @note_selection = Note.references
      @pattern = @scale.midi_generator(60, 1)
      render :edit
    end
  end

  def most_popular
    @most_popular_scale = "Ionian"
  end

  def destroy
    scale = Scale.find(params[:id]).destroy
    editable_scale?(scale)
    redirect_to scales_path
  end

  private
  def scale_params
    params.require(:scale).permit(:name, :scale_type, :origin, :melody_rules, :created_by, :private, :pattern => [])
  end

  def valid_scale?(scale)
    if !scale
      redirect_to scales_path, alert: "Hm, we can't find that scale, sorry!"
      false
    elsif scale.not_your_scale(current_user)
      redirect_to scales_path, alert: "Hey, that's private!"
      false
    else
      true
    end
  end

  def editable_scale?(scale)
    if valid_scale?(scale) && scale.created_by != current_user.id
      go_to(scale, root = "do", alert = "You can't edit this scale, sorry!")
    else
      true
    end
  end

  def go_to(scale, root = "do", alert = nil)
    redirect_to show_scale_path({scale_slug: scale.slugify, root_note: root}), alert: alert
  end


end

app/helpers/scales_helper.rb
module ScalesHelper
  def of_type(scales, type)
    @scales.select{|s|s.scale_type == type}
  end

  def li_for_scale(s)
    content_tag(:li, link_to(s.name, show_scale_path({scale_slug: s.slugify, root_note: "do"})))
  end
end

app/views/scales/_form.html.erb
<%= render :partial => 'layouts/errors', locals: {obj: @scale} %>

<%=content_tag :div, class: ["form"] do%>
  <%=form_for @scale do |f|%>
    <%=f.label :name%><br>
    <%=f.text_field :name%><br>
    <br>
    <%=f.label :scale_type%><br>
    <%=f.text_field :scale_type%><br>
    <br>
    <%=f.label :origin%><br>
    <%=f.text_field :origin%><br>
    <br>
    <%=f.label :melody_rules%><br>
    <%=f.text_area :melody_rules%><br>
    <br>
    <%=f.label :aka, "Also known as"%><br>
    <%=f.text_area :aka%><br>
    <br>
    <div class="pattern_checkboxes">
      <%=f.label :pattern%><br>
      <%=f.collection_check_boxes(:pattern, @note_selection, :midi_value, :solfege, { checked: @pattern.map })%><br>
    </div>
    <br>
    <%= f.label "Would you like to keep this scale private?" %> <br />
    <%= f.check_box :private %> <br />
    <br>
    <%=f.submit submit_text%>
  <%end%>
<%end%>

app/views/scales/index.html.erb
<h1 class="header">SCALE LIBRARY</h1>

<div class="search_bar">
  <form id="search">
    <input type="text" id="search" name="search" placeholder="Find a scale">
    <input type="submit" value="Find!">
  </form>
</div>

<div class="container">
  <!-- <div class="primary_content"> -->
  <!-- <div class="flash-error primary_error"></div> -->
    <%=content_tag :div, class: ["primary_content"] do%>
      <%@types.each do |type|%>
        <%=content_tag :div, class: ["scale_type"], id: ["#{type}"] do%>
          <h2><%=type%></h2>
          <%of_type(@scales, type).each do |s|%>
            <p><%=li_for_scale(s)%></p>
          <%end%> <!-- of_type.each -->
        <%end%> <!-- scale_type -->
      <%end%> <!-- types.each -->
    <%end%> <!-- scales_menu / primary content-->
  <!-- </div> -->

  <div class="sidebar">
    <div class="sb_nav">
      <%=content_tag(:button, link_to("Add a new scale!", new_scale_path), class: ["add_scale"])%>
    </div>
    <div class="sb_header">

    </div>
    <div class="sb_content">

    </div>
    <br></br>
    <div class="sb_errors"></div>
  </div>
</div> <!-- container -->