config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Scales routes
resources :scales, only: [:index, :new, :create, :update, :destroy]
get '/scales/most_popular', to: 'scales#most_popular', as: 'most_popular_scale'
get '/scales/:scale_slug', to: 'scales#show'
get '/scales/:scale_slug/edit', to: 'scales#edit', as: 'edit_scale'
post '/scales/:scale_slug/change_root', to: 'scales#change_root'
get '/scales/:scale_slug/:root_note', to: 'scales#show', as: 'show_scale'



resources :practises, only: [:create]

# Sessions routes
get '/login', to: 'sessions#new', as: 'login'
get '/auth/:provider/callback', to: 'sessions#create' # OAuth callback route
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'

# Users (musicians) routes
resources :musicians, only: [:new, :create]
get '/musicians/rankings/:by', to: 'musicians#rankings', as: 'musician_rankings'
get '/:musician_slug', to: 'musicians#show', as: 'practice_room'

root 'welcome#welcome'


end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    Oops, there's <%= pluralize(obj.errors.count, "error") %>!
    <p><% obj.errors.full_messages.each.with_index(1) do |msg, i| %>
        <%= msg %><%="<br />".html_safe if i != obj.errors.count%>
    <% end %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScaleThis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('scalethistextgh.png'), :rel => 'icon', :type =>  'image/png' %>

    <%= yield :og_header%>
    <%= tag(:meta, property: "twitter:site", content: "@GingertonicSt")%>
  </head>

  <body>

    <div id="navbar">
      <%=link_to "SCALE THIS", root_url, class: "nav-link home-link"%>
      <%if current_user%>
        <%=link_to "Your Practice Room", practice_room_path(current_user.slugify), class: "nav-link"%>
        <%=link_to "Scales Library", scales_path, class: "nav-link"%>
        <%=link_to "Log Out", logout_path, class: "nav-link"%>
      <%else%>
        <%=link_to "Sign Up", new_musician_path, class: "nav-link"%>
        <%=link_to "Sign In", login_path, class: "nav-link"%>
      <%end%>
    </div>

    <%if !flash.empty?%>
      <div class="flash-error">
        <% flash.each do |key, value| %>
          <%= content_tag :div, value, class: "flash #{key}" %>
        <% end %>
      </div>
    <%end%>
    <br />

    <%= yield %>
  </body>
</html>